services:
  postgres:
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${POSTGRES_DATA}
    ports:
      - ${POSTGRES_PORT}:5432
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - postgres-data:${POSTGRES_DATA}

  redis:
    image: redis:7-alpine
    restart: always
    env_file: .env
    ports:
      - ${REDIS_PORT}:6379
    expose:
      - ${REDIS_PORT}
    volumes:
      - redis-data:${REDIS_DATA}
    command: [ "--requirepass", "${REDIS_PASSWORD}" ]

  bot:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - postgres

volumes:
  redis-data:
  postgres-data:
